service: hotelapi

provider:
  name: aws
  runtime: python3.6
  region: us-east-2
#  stage: dev
#  memorySize: 2048
#  versionFunctions: false
  vpc:
    securityGroupIds:
      - sg-09b7d9888c893594d
    subnetIds:
      - subnet-08c1aacead6928c9f
      - subnet-076b9627be0729a38
#  iamRoleStatements:
#    - Effect: 'Allow'
#      Action:
#        - 'ses:SendEmail'
#      Resource: '*'
#    - Effect: 'Allow'
#      Action:
#        - 'rds-db:connect'
#      Resource: '*'

functions:
  validation:
    timeout: 900
    handler: endpoints.api_get
    events:
      - http:
          path: /validation
          method: post
          cors:
            headers:
              - Content-Type
              - Pragma
              - Cache-Control


plugins:
  - serverless-python-requirements
#  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: True
#  prune:
#    automatic: true
#    number: 3
